### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mjmottram** [snoplusuk/echidna#1]
Create one.

**Comment by ashleyrback** [comment]
@mjmottram this issue is still outstanding and is required for the alpha release of echidna!

**Comment by arushanova** [comment]
done

**Comment by pgjones** [comment]
You can add images to issues (see base of edit box), what is the logo?

**Comment by ashleyrback** [comment]
@arushanova sent it in an email to the mailing list, but for completeness
![echidna_logog](https://cloud.githubusercontent.com/assets/1931666/6135023/242dda98-b15d-11e4-85e0-af9dadd76165.png)

**Comment by pgjones** [comment]
Ace
