### ISSUE TITLE
Chi squared bug

### ISSUE THREAD

**Issue by mjmottram** [snoplusuk/echidna#127]
Is this a bug: https://github.com/snoplusuk/echidna/blob/master/echidna/limit/chi_squared.py#L189.  Presumably if observed is < epsilon then you adjust observed, not expected.  I have some optimisations for these functions that I'll add this fix to (if indeed it needs it).

**Comment by ashleyrback** [comment]
Yes this is a typo, it should be:
```python
if observed[i] < epsilon:
    observed[i] = epsilon
```

**Comment by ashleyrback** [comment]
@mjmottram this was fixed in #114.
