### ISSUE TITLE
Sphinx doc build error with ubuntu 

### ISSUE THREAD

**Issue by jwaterfield** [snoplusuk/echidna#13]
I get the following error when making the html using the latest stable release on ubuntu:

sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.1.3

Extension error:
Could not import extension sphinx.ext.napoleon (exception: No module named napoleon)
make: *** [html] Error 1

**Comment by pgjones** [comment]
Hmm, it should report an error before that stating you need sphinx 1.3 or above [see](https://github.com/snoplusuk/echidna/blob/master/docs/conf.py#L26)... anyway you need to upgrade sphinx.

**Comment by jwaterfield** [comment]
Ah yes was the version which was the issue. closes #13

**Comment by harishkashyap** [comment]
I am getting this issue even with sphinx 1.3
