### ISSUE TITLE
Extract data from production ntuples on the Grid

### ISSUE THREAD

**Issue by jwaterfield** [snoplusuk/echidna#24]
Extend the fill_spectrum code so it is compatable with production ntuples located on the grid not just root files generated by rat.

**Comment by ashleyrback** [comment]
@jwaterfield have you tried with ntuples? Did it give an error? If so could you post here please.

**Comment by jwaterfield** [comment]
@ashleyrback the data structure is completely different so fill_spectrum will not work. It is structured so there is just a list of variables within the ntuples and the variable names within the ntuples is different to rat DS.

**Comment by ashleyrback** [comment]
Ah, good point. This also means that `dsreader` probably won't work either.
